### ISSUE TITLE
Argument names not consistent across CLI and python

### ISSUE THREAD

**Issue by JulianNaumann** [lschmelzeisen/nasty#10]
For specifying a maximum number of tweets, in the CLI you need to use the "max-tweets" argument. In python, the same argument is called max_tweets (underscore instead of hyphen).

**Comment by lschmelzeisen** [comment]
Yes, but I don't consider this a bug ;)

For Python, [PEP 8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) dictates that variables and thus parameters should be lowercase, with words separated by underscores. I would prefer to use hyphen here as well, but Python does not allow for hyphens inside of identifiers.

On the CLI side, I couldn't find any agreed upon standard. But the vast majority of programs out there also lowercase all arguments but then separate words with hyphens, see for instance this [table on long options in GNU programs](http://www.gnu.org/prep/standards/html_node/Option-Table.html#Option-Table).

I think it's more important to stay with what is expected in each environment than to enforce consistency in this case.
