### ISSUE TITLE
Problem with `pip install nasty` under Windows: script is not on PATH

### ISSUE THREAD

**Issue by pl1996** [lschmelzeisen/nasty#14]
Hello,

I tried to install nasty via my command line. I have a Windows Laptop and I use Python 3.8.

I first installed pip by installing Python. And then I entered the following comman in the command line:

pip install nasty

and I got this Warning messages:

 WARNING: The script tqdm.exe is installed in 'C:xxx' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script chardetect.exe is installed in 'C:xxx' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script nasty.exe is installed in 'C:xxx' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location

How can I solve this problem and add it to the path? What does it mean?

Thanks in advance!

**Comment by lschmelzeisen** [comment]
Hi, this is an issue related to your own computer setup, not something related to NASTY or for which I could provide support.

In general, the PATH is an environment variable that controls which binaries are visible when you enter them in a command line. For example, you probably won't be able to run `nasty.exe` in your terminal, but `C:\xxx\...\nasty.exe` should work. For more info, check the [Wikipedia page](https://en.wikipedia.org/wiki/PATH_(variable)) and use a search engine of your choice.

**Comment by pl1996** [comment]
Thanks for your help!
