### ISSUE TITLE
Problem regarding the PHOTOS filter.

### ISSUE THREAD

**Issue by ziyad121** [lschmelzeisen/nasty#6]
Hi 
Is the ` filter_="PHOTOS"` means that it retrieves only tweets containing images in them. if so, I guess it doesn't work. 

When using, 

```
tweet_stream = nasty.Search("trump", filter_="PHOTOS",lang="en").request()
```
it doesn't apply the filter.

Thank you.

**Comment by lschmelzeisen** [comment]
The `filter_` parameter expects values from the [SearchFilter](https://github.com/lschmelzeisen/nasty/blob/5891e323690c05938ad390e5c5f624d1337d2923/nasty/request/search.py#L31) enum. Can you try the following?

```python
tweet_stream = nasty.Search("trump", filter_=nasty.SearchFilter.PHOTOS, lang="en").request()
```

**Comment by ziyad121** [comment]
It works now. Thank you
